### ISSUE TITLE
A very special HAT Films gift. (For a very special person to me)

### ISSUE THREAD

**Issue by stygiansabyss** [HatScrubs/GameAccess#42] opened 2016-04-30 19:42 UTC
Submitter: Bram Brouwer
Email: b.brouwer.zakelijk@gmail.com
Dear Lads,

Could you please help me with a very special gift for a very special lady?

I have met thanks you three a very special person (Emily aka Emmy Nyan) whit in the HAT Community .
I would love to celebrate that by giving here a signed HAT bag. The only problem is that I can't go to a convention where you are to get it signed. 
That is why I want to ask if I can mail the bag to your P.O. Box so that you can sign it and that you sand if further to here.
(I will try to cover all the expanses where needed)

Could you please respond if or if it can't work out.

Much love Bram aka sirBrouwer)

**Comment by Akhawais** [comment] 2016-04-30 19:49
Duplicate of #40

**Closed as completed by Akhawais** 2016-04-30 19:49 UTC
Labels: duplicate
